const categories = ["Code-Coding", "Code-Reading", "Code-Other",
    "Shopping", "Cooking", "Cleaning", "Chores", "Chores-Mum",
    "Timesheet", "Morning routine", "Review",
    "Reading",
    "Mind-Meditate", "Mind-Projects", "Mind-Brainstorm", "Mind-Thought experiments", "Mind-Other",
    "Exercise-Walk", "Exercise",
    "Social-Chats-Phone", "Social-Going out",
    "SH-Podcast",
    "Podcast-Misc",
    "TV-YT",
    "Sport-League", "Sport-Cricket", "Sport-Boxing", "Sport-Other",
    "Relaxing",
    "Misc",
    "Investing", "Financial",
    "Health",
    "Wasted-Drunk", "Wasted-Computer",
    "Weekly", "Monthly", "Yearly",
    "Sleep", "Eating"
]
